name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: sudo apt install libgirepository1.0-dev
    - run: pip install -r requirements.txt

    - name: Flake8
      run: flake8 src/

    - name: MyPy
      run: mypy src/

  meson-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: sudo apt-get -y install appstream appstream-util desktop-file-utils gettext

    - name: Meson build
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build

    - name: Meson test
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test

  flatpak-build-test:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Flatpak builder
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: "diffuse.flatpak"
        manifest-path: "io.github.mightycreak.Diffuse.yml"
        cache-key: flatpak-builder-${{ github.sha }}
        run-tests: "true"
